export default {
    DO_NOTHING: -1,
    SET_AREAS: 0,
    SET_INDICATORS: 1,
    SET_ACTIVE_INDICATOR: 2,
    SET_INFO_WINDOW_VISIBILITY_FLAGS: 3,
    TOGGLE_INDICATOR_BRANCH_VISIBILITY: 4,
    TOGGLE_INDICATOR_LEAF_VISIBILITY: 5,
    TOGGLE_INFO_WINDOW_VISIBILITY: 6,
    SET_APP_STATE: 7
}
